chartVersion: 0.1.0
projectName: default-app

ingress:
  host: "mark.onthewifi.com"
  path: /
  pathType: Prefix

deployment:
  replicas: 1
  image: ubuntu-latest
  tag: latest
  pullPolicy: Always

service:
  port: 80
