chartVersion: 0.1.0
projectName: default-app

ingress:
  enabled: true
  host: "mark.onthewifi.com"
  path: /
  pathType: Prefix

deployment:
  enabled: true
  replicas: 1
  image: ubuntu-latest
  tag: latest
  pullPolicy: Always
  env: []

service:
  enabled: true
  port: 80
