chartVersion: 0.2.3

projectName: "portfolio"

project:
  name: "portfolio"

repository:
  name: "markmorcos/portfolio"
  path: "."

ingress:
  host: mark.onthewifi.com
  rules:
    - host: mark.onthewifi.com
      path: /
      pathType: Prefix
      serviceName: portfolio-service

deployments:
  - name: portfolio
    image: markmorcos/portfolio

services:
  - name: portfolio-service
    port: 80
