services:
  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile.development
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./landing
          target: /app
          ignore:
            - node_modules
