apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-deployment
  namespace: {{ .Values.projectName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
    spec:
      containers:
        - name: {{ .Values.projectName }}
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
