apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
    spec:
      containers:
        - name: {{ .Values.projectName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
