apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectName }}-service
  namespace: {{ .Values.projectName }}
spec:
  selector:
    app: {{ .Values.projectName }}
  ports:
    - name: {{ .Values.projectName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
