chartVersion: 0.2.5

project:
  name: infrastructure-admin

repository:
  name: markmorcos/infrastructure
  path: admin

ingress:
  host: infra.morcos.tech
  rules:
    - host: infra.morcos.tech
      path: /?(.*)
      pathType: ImplementationSpecific
      serviceName: infrastructure-admin-service

deployments:
  - name: infrastructure-admin-deployment
    image: markmorcos/infrastructure-admin
    env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            key: DATABASE_URL
            name: database-secrets
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            key: JWT_SECRET
            name: jwt-secret

services:
  - name: infrastructure-admin-service
    port: 3000
