{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.project.name }}
spec:
  replicas: {{ .replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ $.Values.project.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.project.name }}
        build-timestamp: '{{ now | date "20060102150405" }}'
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          env:
{{ toYaml .env | indent 12 }}
{{- end }}
