{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.project.name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
        app: {{ $.Values.project.name }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          env:
{{ toYaml .env | indent 12 }}
{{- end }}
