{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.project.name }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      labels:
        app: {{ $.Values.project.name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .name }}
          image: "{{ .image | default (pluck "image" $.Values.deployments | first) }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          command: {{ toJson .command }}
          env:
{{ toYaml (.env | default (pluck "env" $.Values.deployments | first)) | indent 12 }}
{{- end }}
