name: Apply Kubernetes Manifests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths: ["k8s/**"]

jobs:
  apply-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.RASPBERRY_PI_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Loop and apply YAMLs over SSH stdin
        run: |
          echo "${{ secrets.RASPBERRY_PI_SSH_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

          cat k8s/*.yaml | ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no \
          "${{ secrets.RASPBERRY_PI_USERNAME }}@${{ secrets.RASPBERRY_PI_HOST }}" \
          "export KUBECONFIG=/home/mark/.kube/config && kubectl apply -f -"
