name: publish-charts

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "charts/infrastructure/Chart.yaml"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current chart version
        id: chart_version
        run: |
          version=$(grep '^version:' charts/infrastructure/Chart.yaml | awk '{print $2}')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Fetch previous commit
        run: git fetch origin main --depth=2

      - name: Check if Chart.yaml version changed
        id: version_changed
        run: |
          if git diff HEAD^ -- charts/infrastructure/Chart.yaml | grep '^+version:'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip if version didn't change
        if: steps.version_changed.outputs.changed == 'false'
        run: echo "Chart version unchanged. Skipping publish."

      - name: Package chart
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          helm package charts/infrastructure

      - name: Login to GHCR
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          echo "${{ secrets.INFRASTRUCTURE_PAT }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Push chart to GHCR
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          helm push infrastructure-${{ steps.chart_version.outputs.version }}.tgz \
            oci://ghcr.io/markmorcos
