name: smart

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "smart/**"
  pull_request:
    branches:
      - main
    paths:
      - "smart/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd smart
          npm ci
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd smart
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t markmorcos/home-server-smart:$IMAGE_TAG -t markmorcos/home-server-smart:latest -f Dockerfile.production .
          docker push markmorcos/home-server-smart:$IMAGE_TAG
          docker push markmorcos/home-server-smart:latest

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.RASPBERRY_PI_HOST }}
          key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            cd /home/pi/smart
            git pull
            docker pull markmorcos/home-server-smart:latest
            k3s kubectl set image deployment/smart-depl smart=markmorcos/home-server-smart:$IMAGE_TAG
